### ISSUE TITLE
omxplayer flickers with subtitles

### ISSUE THREAD

**Issue by phixofor** [blissland/blissflixx#28]
When playing a video file, the -b (black background option) causes omxplayer to flicker uncontrollably if the video has subtitles.

**Comment by blissland** [comment]
This would appear to be an omxplayer issue rather than something I can fix in blissflixx

**Comment by phixofor** [comment]
Yes, you are completely right, but does the -b flag need to be applied?

**Comment by blissland** [comment]
>> but does the -b flag need to be applied?

Mmm - I can't remember the reason for adding it or if it still needs to be
there. You can try removing it and see what happens. The place you need to
edit is at the top of the file:

blissflixx/lib/player/omxproc2.py

I'm afraid I'm away from my setup at the moment so cannot test this change
myself.

**Comment by phixofor** [comment]
I tested it, and recompiled into .pyc – works great now. Not sure if it is a problem with omxplayer or my cheap IKEA TV :)

Unless you have something to add about this you can close this as it is resolved, for my part. Thanks for a great product.

**Comment by blissland** [comment]
I will test the change on my setup (later) and see if we still need the -b flag or not

**Comment by blissland** [comment]
Have removed the -b flag
