### ISSUE TITLE
[Feature Request] Multimedia Keys

### ISSUE THREAD

**Issue by markuznw** [blissland/blissflixx#30]
Hello, thank you for the awesome software! Would it be possible to add support for multimedia keys from external wifi keyboard? I am using a ProMini RF-Touch 3 that is a little wifi keyboard with touchpad and multimedia keys. Keys are working in raspbian (they raise lower and mute volume) but not on blissflixx. Same goes for pause/play forward etc buttons :)
Thanks in advance :)

**Comment by blissland** [comment]
All controls for the player come from the web client. There is currently no support for responding to events from the local keyboard as blissflixx runs as a background service. I don't see any easy way to implement this I'm afraid.

**Comment by markuznw** [comment]
Oh, that's so unfortunate, I hope you will be able to find a solution in the future as I think it's like a... main feature for a multimedia player :P

**Comment by diegorodriguezv** [comment]
I have looked into this and agree with Mr. @blissland that it's (almost) impossible.
