### ISSUE TITLE
BBC iPlayer playback lag

### ISSUE THREAD

**Issue by jerheij** [blissland/blissflixx#33]
I am experiencing lag/stuttering with the playback of BBC iPlayer, the ITV playback works smoothly. I've tried playing around with the omxplayer buffer settings which didn't help. My setup:
- Raspberry Pi 3 B  	  	   	   	 
- 16GB SanDisk Ultra Micro SDHC 80mb/s  	 
- 3A Micro USB PSU  	 
- LAN wired network connection
- Newest and updated raspbian (disabled GUI to minizime memory/CPU usage)

I noticed that the playback of ITV uses a "localhost" link while the BBC playback used some external link, could the issue be because of that?

**Comment by blissland** [comment]
Not sure at the moment what the issue might be. BBC iplayer is working fine for me. You could try downloading a BBC program directly using youtube-dl and then running it manually through omxplayer. If you still get the issue it is a omxplayer problem otherwise it is something in BlissFlixx.

**Comment by jerheij** [comment]
Are there any specific configurations in Raspbian / on the RPI you're using I might have missed?

**Comment by blissland** [comment]
No specific configurations - just out of the box Raspbian.

youtube-dl is included as part of  BlissFlixx. To download a BBC program:

`cd blissflixx/lib/youtube-dl`

Then:

`python -m youtube_dl <BBC URL>`

e.g

`python -m youtube_dl http://www.bbc.co.uk/iplayer/episode/b08w9248/matilda-and-the-ramsay-bunch-series-3-8-the-wedding-anniversary`

Then play the downloaded file through omxplayer:

`omxplayer <name of file>`

**Comment by jerheij** [comment]
I keep getting the following error when I am trying to youtube_dl something from bbc.co.uk:

> WARNING: Failed to download m3u8 information: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:581)>
[dashsegments] Total fragments: 451
[download] Destination: EastEnders, 22_06_2017-b08w4zc4.fstream-uk-iptv_streaming_concrete_combined_hd_mf_limelight_uk_dash_https-video=5070000.mp4
[download] 100% of 1.00GiB in 08:52
[dashsegments] Total fragments: 451
[download] Destination: EastEnders, 22_06_2017-b08w4zc4.fstream-uk-iptv_streaming_concrete_combined_hd_mf_limelight_uk_dash_https-audio_eng=128000.m4a
[download] 100% of 26.20MiB in 03:13
[ffmpeg] Merging formats into "EastEnders, 22_06_2017-b08w4zc4.mp4"
ERROR: Could not write header for output file #0 (incorrect codec parameters ?): Operation not permitted

**Comment by blissland** [comment]
Sorry for the delay in replying.

Try adding the -f best switch. e.g.

`python -m youtube_dl -f best <URL>`

**Comment by jerheij** [comment]
Something I noticed when I am trying to download something from BBC iPlayer is that the connection is < 1MBps, when I download something from youtube with youtube_dl then I get a speed up to 10MBps. Even when downloading longer youtube vids.

Is it possible that the lag is caused by the obtainable speed from BBC iPlayer?

**Comment by jerheij** [comment]
Is there any chance you'll be able to help me resolve this issue? 

Thanks in advance!

**Comment by jerheij** [comment]
This seems to mostly work smoothly now.
