### ISSUE TITLE
Cannot play programs with ITV iPlayer

### ISSUE THREAD

**Issue by stevedee** [blissland/blissflixx#38]
(I thought this project had died, but just noticed you have fixed the latest iPlayer issue. Thanks Mr.Bliss).

This problem with ITV player has existed since the summer when (I think) the service started to require a log-in or something.

When selecting any program I get an error shortly after starting to load, usually:-

"Process exit: 1"

...or sometimes;

"Process suddenly died"

**Comment by blissland** [comment]
I did a fix for the ITV player issue on November 5. Make sure you have updated to the latest version of everything.

**Comment by stevedee** [comment]
Sorry Mr.Bliss, I'm an idiot. I have only been checking code top level "Last commits" so I missed this one.
Now all is good.
