### ISSUE TITLE
Soundcloud not part of the channels

### ISSUE THREAD

**Issue by sandoche** [blissland/blissflixx#39]
As you can see int he screenshots I don't see soundcloud in the list of channels.

![capture d ecran de 2018-06-12 19-21-54](https://user-images.githubusercontent.com/3635348/41306289-ee4a759c-6e75-11e8-805c-4e19d6eaa08e.png)
![capture d ecran de 2018-06-12 19-22-12](https://user-images.githubusercontent.com/3635348/41306290-ee73d09a-6e75-11e8-9987-eadbd42cafb1.png)
![capture d ecran de 2018-06-12 19-22-15](https://user-images.githubusercontent.com/3635348/41306292-ee93c6f2-6e75-11e8-893c-777b38181392.png)

That's the only missing channel otherwise Blissflixx works very well!

**Comment by diegorodriguezv** [comment]
I just added a SoundCloud channel. 
Please keep in mind some tracks are unavailable in some countries so you may get an 'Unable to download JSON metadata' error when trying to stream a restricted track. Any feedback is welcome.

**Comment by blissland** [comment]
Works great! - Thanks for that.
