### ISSUE TITLE
Error 500: blissflixx.rocks is down

### ISSUE THREAD

**Issue by diegorodriguezv** [blissland/blissflixx#42]
:( 
Has "the man" shut it down?

**Comment by blissland** [comment]
I'm afraid so.

**Comment by diegorodriguezv** [comment]
Is there anything we can do to help?

**Comment by omody** [comment]
Mr Blissland
Can you clarify - did you shut it down or it was shutdown for some reason?
Big Fan!

**Comment by diegorodriguezv** [comment]
Could you open source the blissflixx.rocks server so we could try to run a local copy? Or at least the json files?

**Comment by blissland** [comment]
OK so what happened is that I did not renew the domain blissflixx.rocks since I figured nobody was really using it. However due to popular demand ;-) I have since renewed the domain so everything should be back once the DNS has fully propagated.

**Comment by diegorodriguezv** [comment]
Good news. 
Anyway removing dependency on blissflixx.rocks seems like a good idea.
Thanks a lot. Awesome project!

**Comment by omody** [comment]
Is there way to also have a pyinstaller or nautika build created to make the install process easier?
