### ISSUE TITLE
Install on raspberry pi debian 11 bullseye 

### ISSUE THREAD

**Issue by waltersheets** [blissland/blissflixx#86]

**Comment by diegorodriguezv** [comment]
Unfortunately Debian 11 doesn't have omxplayer in it's packages.
As mentioned in the [website](https://diegorodriguezv.github.io/blissflixx/):

If you really need Raspberry PI OS 11 (Bullseye):
start by installing Buster
run configure.sh
do a distupgrade to bullseye
run the configure.sh script again
This way OmxPlayer gets installed in Buster but remains when updating to Bullseye.
